// <auto-generated />
using ItspTest.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItspTest.Core.Migrations.Collection
{
    [DbContext(typeof(CollectionContext))]
    [Migration("20220310192541_Initial-CollectionDB")]
    partial class InitialCollectionDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItspTest.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ItspTest.Core.Models.UserCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCollections");
                });

            modelBuilder.Entity("ItspTest.Core.Models.UserMovieCollection", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserCollectionId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "UserCollectionId");

                    b.HasIndex("UserCollectionId");

                    b.ToTable("UserMovieCollections");
                });

            modelBuilder.Entity("ItspTest.Core.Models.UserMovieCollection", b =>
                {
                    b.HasOne("ItspTest.Core.Models.Movie", "Movie")
                        .WithMany("UserMovieCollections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItspTest.Core.Models.UserCollection", "UserCollection")
                        .WithMany("UserMovieCollections")
                        .HasForeignKey("UserCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("UserCollection");
                });

            modelBuilder.Entity("ItspTest.Core.Models.Movie", b =>
                {
                    b.Navigation("UserMovieCollections");
                });

            modelBuilder.Entity("ItspTest.Core.Models.UserCollection", b =>
                {
                    b.Navigation("UserMovieCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
